### ISSUE TITLE
Make Some constructor visible

### ISSUE THREAD

**Issue by peter-tackage** [peter-tackage/kotlin-options#4]
Currently the constructor for `Some` is marked `internal`. I am now thinking that there's no benefit to not exposing it and preventing direct instantiation as:

1. We already expose the `Some` and `None` classes, so these types are known by library clients.
2. By ensuring the `Some` constructor only takes `<T : Any>` we prevent incorrect creation or require `checkNotNull` like in Java - there's no run time risk.
3. For readability purposes, it would make defining a specific `Option` value clearer when using non-nulls than requiring use of `optionOf`. It could just be `Some("abc")`.

Thoughts? @tomaszpolanski

**Comment by tomaszpolanski** [comment]
I see one issue:
If we get a value from outside of kotlin, for example, `String!`, this thing would allow to be passed to Some. In that case, we would have some with possible null

**Comment by peter-tackage** [comment]
True. The question then becomes, if we can't trust the calling code to use `T!` appropriately (that is; treat it as `T?`), could we trust them to use `optionOf` if that was the only creator method available?

**Comment by peter-tackage** [comment]
If the `Some` constructor is exposed, only the initial creation will be unsafe for `T!` - Kotlin fails fast if you attempt to use a `null` value for `T : Any`.

**Comment by tomaszpolanski** [comment]
The reason why I like `optionOf` being the only way to create `Some` is that we are sure that it will never have inconsistent state. And people will be using those options mainly with stuff that comes from the system (`T!`)

**Comment by peter-tackage** [comment]
With the current: `internal constructor` we can still use `Some("abc")`, so we aren't forced to use `optionOf` for tests (at least in `OptionTest`)

**Comment by peter-tackage** [comment]
I'm going to leave it out of the API, but update `OptionTest` to use it.
